# Site settings
title: DemoPro Analytics Solution
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  DemoPro Project Page
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  DemoPro-AnalyticsSolution

# Build settings
markdown: kramdown
